export const ENEMY_TYPES = {
    COMMON: {
        name: 'Pez Común',
        color: 0x4a9fff,
        size: 15,
        speed: 80,
        health: 1,
        damage: 0,
        dnaType: 'speed',
        dnaAmount: 5,
        behavior: 'flee',
        hungerRestore: 15,
        spawnWeight: 35
    },
    PUFFER: {
        name: 'Pez Globo',
        color: 0xff8c00,
        size: 25,
        speed: 40,
        health: 3,
        damage: 0,
        dnaType: 'defense',
        dnaAmount: 8,
        behavior: 'wander',
        hungerRestore: 25,
        spawnWeight: 20
    },
    HUNTER: {
        name: 'Pez Cazador',
        color: 0xff3333,
        size: 20,
        speed: 70,
        health: 2,
        damage: 10,
        dnaType: 'attack',
        dnaAmount: 10,
        behavior: 'chase',
        hungerRestore: 20,
        spawnWeight: 15
    },
    LUMINOUS: {
        name: 'Pez Luminoso',
        color: 0xffff00,
        size: 12,
        speed: 120,
        health: 1,
        damage: 0,
        dnaType: 'energy',
        dnaAmount: 15,
        behavior: 'flee',
        hungerRestore: 10,
        spawnWeight: 8
    },
    MUTANT: {
        name: 'Pez Mutante',
        color: 0x9932cc,
        size: 30,
        speed: 60,
        health: 5,
        damage: 15,
        dnaType: 'random',
        dnaAmount: 20,
        behavior: 'chase',
        hungerRestore: 35,
        spawnWeight: 4
    },
    // New enemy types
    TOXIC: {
        name: 'Pez Tóxico',
        color: 0x00ff00,
        size: 18,
        speed: 50,
        health: 2,
        damage: 5,
        dnaType: 'defense',
        dnaAmount: 12,
        behavior: 'wander',
        hungerRestore: 18,
        spawnWeight: 10,
        special: 'poison'
    },
    ANGLERFISH: {
        name: 'Pez Abisal',
        color: 0x2a1a4a,
        size: 35,
        speed: 30,
        health: 4,
        damage: 20,
        dnaType: 'energy',
        dnaAmount: 25,
        behavior: 'ambush',
        hungerRestore: 40,
        spawnWeight: 3,
        special: 'lure'
    },
    JELLYFISH: {
        name: 'Medusa',
        color: 0xff88cc,
        size: 22,
        speed: 20,
        health: 1,
        damage: 8,
        dnaType: 'energy',
        dnaAmount: 10,
        behavior: 'float',
        hungerRestore: 12,
        spawnWeight: 12,
        special: 'sting'
    },
    SHARK: {
        name: 'Tiburón',
        color: 0x555577,
        size: 45,
        speed: 90,
        health: 8,
        damage: 25,
        dnaType: 'attack',
        dnaAmount: 30,
        behavior: 'hunt',
        hungerRestore: 50,
        spawnWeight: 2,
        special: 'frenzy'
    },
    ELECTRIC_EEL: {
        name: 'Anguila Eléctrica',
        color: 0x00ccff,
        size: 28,
        speed: 65,
        health: 3,
        damage: 12,
        dnaType: 'energy',
        dnaAmount: 18,
        behavior: 'patrol',
        hungerRestore: 22,
        spawnWeight: 6,
        special: 'shock'
    },
    CAMOUFLAGE: {
        name: 'Pez Camuflado',
        color: 0x8b7355,
        size: 20,
        speed: 100,
        health: 2,
        damage: 15,
        dnaType: 'speed',
        dnaAmount: 12,
        behavior: 'ambush',
        hungerRestore: 20,
        spawnWeight: 5,
        special: 'invisible'
    }
};

export const DNA_TYPES = ['speed', 'defense', 'attack', 'energy'];
